
[Server]
	#Limit item tags to particular size. 
	#It prevents a huge Cartesian multiplication for recipes consist of several long tags. 
	#Zero means no limitation. 
	#Default: 1
	#Range: 0 ~ 5
	tag_limit = 1
	#Allows recipes that haven't explored yet. 
	#Default: false
	allow_unexplored_recipes = false
	#Allows shared access to the same table. 
	#Default: false
	allow_shared_access = false

